services:
  # --- NODO MAESTRO DE SPARK ---
  spark-master:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_HOST=0.0.0.0 # Obliga a Spark a escuchar en tu IP física, no solo local
    ports:
      - "8080:8081" # <--- CAMBIO CRÍTICO: Mapea el 8081 interno de Bitnami al 8080 de tu red física
      - "7077:7077" # Puerto de comunicación para los Workers
    volumes:
      - ./app:/app

  # --- CLIENTE AUTOMATIZADO ---
  spark-cliente:
    image: bitnamilegacy/spark:3.5.1
    container_name: spark-cliente
    volumes:
      - ./app:/app
    command: sh -c "sleep 10 && spark-submit --master spark://10.13.140.92:7077 /app/procesamiento.py"
    depends_on:
      - spark-master